### ISSUE TITLE
gdb-static-cross submodule is using ssh

### ISSUE THREAD

**Issue by luser** [mzpqnxow/embedded-toolkit#1]
I tried cloning this repo with `git clone --recursive` but it failed:
```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://github.com/mzpqnxow/gdb-static-cross' into submodule path '/build/embedded-toolkit/build_scripts/gdb-static-cross' failed
```

I think this probably ought to be https://github.com/mzpqnxow/gdb-static-cross/ to make this work reliably:
https://github.com/mzpqnxow/embedded-toolkit/blob/89c2e5d250bd18dfe5b43307ecde958a9a138613/.gitmodules#L3

**Comment by mzpqnxow** [comment]
@luser Yes, that would be a saner default, I hadn't really thought of users making use of https (I always use ssh via an "insteadOf" in my ~/.gitconfig) so I never noticed the issue. Not all users clone with their SSH key handy (or even *have* an SSH key) so I will address this.

I changed it to https, give it a try to confirm when you get a chance.

Thanks!
